### ISSUE TITLE
Game crash, I saw you wanted the log...

### ISSUE THREAD

**Issue by Swifty744** [Tynoxs/BuildersDelight#27] opened 2024-04-01 15:16 UTC
https://pastebin.com/2WpLF4gQ

I can't paste it because the error log is so long. I saw you requested the log so I popped it into a pastebin, it only happeens with the latest version of builders delight.

**Comment by Tynoxs** [comment] 2024-04-01 17:04
Thanks,

`Caused by 0: java.lang.NoClassDefFoundError: com/tynoxs/buildersdelight/content/item/BdFurnitureKit`

It's because I changed the furniture kit. 
Every Compat already fixed this. The fix will be in the next version of Every Compat.

**Closed as completed by Tynoxs** 2024-04-01 17:04 UTC
